[phishtank]
username = ''
password = ''
url = 'http://data.phishtank.com/data/online-valid.csv'
last_seen = ''

[openphish]
url = 'https://openphish.com/feed.txt'

[collector]
kit_directory = 'kits'
max_links_per_directory = 100
